In [23]:
import pandas as pd
import numpy as np
from rank_bm25 import BM25Okapi
from langchain_community.retrievers import BM25Retriever
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import re
import pickle
from langchain_openai import OpenAIEmbeddings
import faiss

In [2]:
meta = pd.read_json("../data/raw/meta_Toys_and_Games.jsonl", lines = True, nrows=10000)
review = pd.read_json("../data/raw/Toys_and_Games.jsonl", lines = True, nrows=10000)

<div class="alert alert-info">
    
### Step 1: Data Exploration and Preprocessing
</div>

In [3]:
review.dtypes

rating                        int64
title                           str
text                            str
images                       object
asin                            str
parent_asin                     str
user_id                         str
timestamp            datetime64[ms]
helpful_vote                  int64
verified_purchase              bool
dtype: object

In [4]:
meta.dtypes

main_category          str
title                  str
average_rating     float64
rating_number        int64
features            object
description         object
price              float64
images              object
videos              object
store                  str
categories          object
details             object
parent_asin            str
bought_together    float64
subtitle               str
author              object
dtype: object

In [5]:
cleaned_meta = meta.drop(columns = ['videos', 'price', 'images', 'bought_together', 'subtitle', 'author'])
cleaned_meta.head()

,main_category,title,average_rating,rating_number,features,description,store,categories,details,parent_asin
0,Toys & Games,"KUNGOON Happy Anniversary Balloon Banner,Weddi...",4.5,241,[],[],Kunggo,[],{'Package Dimensions': '10.12 x 8.03 x 0.51 in...,B08GPM7CQN
1,Toys & Games,Gothic Mothman Plushie Doll with Bright Red Ey...,1.3,2,[🦋 Mothman’s bright red eyes could stare you d...,[🦋 Description: Mothman’s bright red eyes coul...,Felicy,"[Toys & Games, Stuffed Animals & Plush Toys, P...","{'Item Weight': '2.47 ounces', 'Manufacturer r...",B09X9XW42H
2,Toys & Games,Melody Jane Dollhouse Builders DIY 1:24 Scale ...,4.2,67,[1:24 Scale - Plastic - Approximate cut out si...,[],Melody Jane Dolls Houses,"[Toys & Games, Dolls & Accessories, Dollhouse ...","{'Item Weight': '0.48 ounces', 'Manufacturer r...",B01I9QET6M
3,Toys & Games,Traxxas Stampede 4X4: 1/10 Scale 4wd Monster T...,4.5,48,[Waterproof electronics for all-weather drivin...,[Stampede 4X4 is built Traxxas Tough to withst...,Traxxas,"[Toys & Games, Remote & App Controlled Vehicle...",{'Product Dimensions': '15.63 x 13.39 x 8.94 i...,B019XEEX1A
4,Toys & Games,Hot Wheels Monster Truck 1:24 Scale 2022 Bone ...,4.8,17699,[Designed in 1:24 scale with durable die-cast ...,[The Hot Wheels Monster Trucks 1:24 scale die-...,Hot Wheels,"[Toys & Games, Preschool, Pre-Kindergarten Toys]",{'Product Dimensions': '5 x 6.27 x 5.5 inches'...,B09G7K3JWQ

In [6]:
reviews = review[review['verified_purchase'] == True]
cleaned_reviews = reviews.drop(columns = ['images', 'timestamp', 'user_id', 'verified_purchase'])
cleaned_reviews.head()

,rating,title,text,asin,parent_asin,helpful_vote
0,5,Granddaughters love them!,I purchased several of these for my granddaugh...,B09QH7QJS7,B09QH7QJS7,0
1,3,Arrived broken,"It’s cute, but it arrived broken & has some pr...",B06XYKSKQP,B06XYKSKQP,1
2,5,Dylan loves them!!!,Bough for my grandson Dylan. He loves them.,B07SFF3YQW,B07XRSD5R9,0
3,5,Janod quality and very cute...,This was great for my daughters circus themed ...,B007JWWUDW,B007JWWUDW,0
4,3,I used for my daughters circus birthday party ...,This is very cute but beware that the animals ...,B00MZG6OO8,B00MZG6OO8,2

In [7]:
parent_asin = list(pd.Series(np.intersect1d(cleaned_reviews['parent_asin'], cleaned_meta['parent_asin'])))

cleaned_reviews = cleaned_reviews[cleaned_reviews['parent_asin'].isin(parent_asin)]
cleaned_meta = cleaned_meta[cleaned_meta['parent_asin'].isin(parent_asin)]

In [9]:
cleaned_meta['description'] = cleaned_meta['description'].apply(
    lambda x: " ".join(x) if isinstance(x, list) else (x if isinstance(x, str) else "")
)
cleaned_meta['description']

128     WizKids Deep Cuts come with highly-detailed fi...
192
213     Mighty missions call for a mighty team vehicle...
318
408
                              ...
9450    Perfection in the palm of your hand, Palm Pals...
9688
9795    Visual perceptions, dexterity and creative thi...
9925
9995
Name: description, Length: 144, dtype: str

In [10]:
cleaned_meta['details'] = cleaned_meta['details'].apply(
    lambda x: " ".join([f"{k} {v}" for k, v in x.items()]) if isinstance(x, dict) else ""
)
cleaned_meta['details']

128     Product Dimensions 5 x 6.5 x 1.5 inches Item W...
192     Product Dimensions 7.09 x 5.91 x 3.15 inches I...
213     Product Dimensions 22 x 8 x 16 inches Item Wei...
318     Product Dimensions 12.4 x 6.9 x 6.9 inches Ite...
408     Package Dimensions 16 x 13.06 x 4 inches Item ...
                              ...
9450    Product Dimensions 4 x 4 x 5 inches Item Weigh...
9688    Package Dimensions 11.06 x 7.83 x 0.87 inches ...
9795    Brand MindWare Age Range (Description) Kid The...
9925    Product Dimensions 12 x 5 x 19 inches Item Wei...
9995    Fill Material Polyester Pillow Type Bed Pillow...
Name: details, Length: 144, dtype: str

In [14]:
cleaned_meta['features'] = cleaned_meta['features'].apply(
    lambda x: " ".join(x) if isinstance(x, list) else ""
)
cleaned_meta['features']

128     Features characters, monsters, and scenery Lit...
192     cotton Main material 100% cotton, allergy & sk...
213     2-IN-1 TRANSFORMING JET: Switch from deluxe je...
318     ►Activity Cube:Includes 12.4x6.9x 6.9 inch woo...
408     ❤Super Value - Eight Cute plush doll in each b...
                              ...
9450    5 inches long from top to bottom High quality ...
9688    Polyester 🌟【Kids Chef Hat Apron Set】: Children...
9795    Fun and educational toys for children all ages...
9925    The bricks are Very Tiny, please look over the...
9995    Microfiber,polyester SUPER SOFT & GREAT SUPPOR...
Name: features, Length: 144, dtype: str

In [11]:
cleaned_meta['categories'] = cleaned_meta['categories'].apply(
    lambda x: " ".join(x) if isinstance(x, list) else ""
)
cleaned_meta['categories']

128          Toys & Games Games & Accessories Board Games
192     Toys & Games Preschool Pre-Kindergarten Toys S...
213     Toys & Games Preschool Pre-Kindergarten Toys P...
318     Toys & Games Baby & Toddler Toys Early Develop...
408     Toys & Games Stuffed Animals & Plush Toys Plus...
                              ...
9450    Toys & Games Preschool Pre-Kindergarten Toys S...
9688    Toys & Games Dress Up & Pretend Play Kitchen T...
9795        Toys & Games Arts & Crafts Craft Kits Mosaics
9925    Toys & Games Preschool Pre-Kindergarten Toys A...
9995    Toys & Games Stuffed Animals & Plush Toys Plus...
Name: categories, Length: 144, dtype: str

##### Description of text preprocessing decisions

<div class="alert alert-info">
    
### Step 2 and 3: BM25 Search and Semantic Search
</div>

In [ ]:
# code adapted from lecture 5

# combining all the important and useful columns from the meta dataset
products = (
    cleaned_meta['title'].fillna('') + ' ' +
    cleaned_meta['description'].fillna('') + ' ' +
    cleaned_meta['features'].fillna('') + ' ' +
    cleaned_meta['categories'].fillna('')
)
products = products.tolist()
queries = cleaned_reviews['title'].tolist()

def simple_tokenize(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    return text.split()

tokenized_products = [simple_tokenize(p) for p in products]
bm25 = BM25Okapi(tokenized_products)

model = SentenceTransformer("all-MiniLM-L6-v2")
product_embeddings = model.encode(products).astype("float32")

# using faiss to index product embeddings for semantic search
index = faiss.IndexFlatL2(product_embeddings.shape[1])
index.add(product_embeddings)

def bm25_search(query, top_k=3):
    tokenized_query = simple_tokenize(query)
    scores = bm25.get_scores(tokenized_query)
    ranked_idx = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:top_k]
    return [(products[i], scores[i]) for i in ranked_idx]

def embedding_search(query, top_k=3):
    query_embedding = model.encode([query]).astype("float32")
    distances, indices = index.search(query_embedding, top_k)
    return [(products[i], distances[0][rank]) for rank, i in enumerate(indices[0])]

for q in queries:
    print("=" * 80)
    print(f"QUERY: {q}\n")

    print("BM25 top results:")
    for rank, (product, score) in enumerate(bm25_search(q), start=1):
        print(f"{rank}. ({score:.3f}) {product}")

    print("\nEmbedding search top results:")
    for rank, (product, score) in enumerate(embedding_search(q), start=1):
        print(f"{rank}. ({score:.3f}) {product}")
    print()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

================================================================================
QUERY: ADORABLE

BM25 top results:
1. (4.382) Big Time Toys Sea Monkeys Ocean Zoo Deluxe Kit Set- Colors May Vary The original, amazing live sea monkeys a classic set to create your very own adorable Aqua-Pets The plastic aquarium is equipped with a ventilated lid, built-in magnifiers and molded seascape bottom Tank measures 5.625" tall ****Please note that results of egg hatched VARY for packages**** Your Sea Monkey pets MAY live up to two years The original, amazing live sea monkeys a classic set to create your very own adorable Aqua-Pets The plastic aquarium is equipped with a ventilated lid, built-in magnifiers and molded seascape bottom Tank measures 5.625" tall Your Sea Monkey pets may live up to two years Toys & Games STEM Toys Science Nature Exploration Toys
2. (4.180) Worlds Smallest Good Luck Trolls. Mini 1 inch Tall Toy Action Figure with an Extra 1.5 inches of Hair! Six Adorable Good Luck Trolls to Collect! Great for School Project, Arts Crafts, Party Favors For over 60 years, Good Luck Trolls have provided the world with adorable smiling faces, round gem bellies, and the best hairstyles ever! There are six Good Luck Trolls to collect in this assortment. Each are sold separately. Measuring only 1 inch tall, these fuzzy headed cuties also have an extra 1.5 inches of hair! Each Troll doll comes with a good luck gemstone in its belly to match the color of its hair. Keep rubbing their bellies for good luck in the years to come! A perfect Easter basket stuffer, stocking stuffer, party favor and more! For Trolls fans of all ages. Recommended for ages 6 and up. Toys & Games Dolls & Accessories Dolls
3. (3.586) Aurora - Palm Pals - 5" Change Chameleon Perfection in the palm of your hand, Palm Pals are the sweetest plush with understuffed bodies and adorable styles Change Chameleon is a mint green reptile with a curly tail 5 inches long from top to bottom High quality materials make for a soft, fluffy touch Sweet, lovable facial expression Collect all Palm Pals to have a #palmpalsparty! To ensure stability and quality, this plush contains bean pellets suitable for all ages Toys & Games Preschool Pre-Kindergarten Toys Stuffed Animals & Toys

Embedding search top results:
1. (1.258) TeeTurtle - The Original Reversible Octopus Plushie - Black + Rainbow - Cute Sensory Fidget Stuffed Animals That Show Your Mood TeeTurtle is the home of the original Reversible Octopus Plushie! Show your mood to the world with this cute reversible plush Octopus, as seen on TikTok! They are easy to flip inside out, and have two different faces to help you express yourself. These super soft toys are perfect for playing, collecting, and cuddling. They make the perfect gift for holidays, birthdays, baby showers, Christmas, Valentine’s Day, and more! Reversible Octopus Plushies are protected by multiple U.S. Copyright Registrations including Registration No. VA0002103871, U.S. Design Patent Nos. D836,168; D822,127; and D860,337, U.S. Utility Patent No. 10,786,746 B2 and trade dress rights under the Lanham Act. This award-winning, #1 best-selling plushie is super soft, portable, and satisfying to flip! Finally, an easy (and cuddly) tool for effective emotional communication. Relieve stress by letting the Reversible Plushie tell friends, family, or coworkers how you are feeling. The perfect work-from-home tool to let friends and family know when not to bother you! Happy= come on in, and Angry= come back later! Collect all the Reversible Plushie stuffed animals, including unicorns, narwhals, cats, dogs, pandas, turtles, and more, in tons of different colors! TeeTurtle Reversible Plushies are a viral TikTok sensation! Your favorite creators have them, and now you can too! Toys & Games Preschool Pre-Kindergarten Toys Stuffed Animals & Toys
2. (1.278) SHDZKJ Cute Bag of Plush Toy Soft Throw Pillow Stuffed Animal Toys Creative Gifts Room Decor (Blue)  ❤Super Value - Eight Cute plush doll in each bag have different vivid expressions. This plushies pillow So cute! ❤Material - Made of elastic velvet&PP cotton.Super soft,warm and comfortable for hugging.Children of all ages will love these cute stuffed animals. ❤Creative gift - The cute toys are the best gift to your babies, lovers, friends.The removable plush toys will be a surprise! ❤Great choise for both adult and kids, sofa back, throw pillow.This cute plushie pillow offers you the best experience resting your head and back. ❤A perfect decoration - To your bedroom, living room and generally every place you like to relax in. Eye-catching pillows will definitely become the main attraction in your house for every guest! Toys & Games Stuffed Animals & Plush Toys Plush Pillows
3. (1.285) PixieCrush Narwhal Unique Stuffed Animals for Girls Ages 3 4 5 6 7 8 Years; Snugababies Stuffed Mommy Narwhal with 4 Baby Narwhals in her Tummy; Toy Plush Pillows for Girls  FIVE TOYS IN ONE : The stuffed mommy narwhal comes with a surprise in her belly, 4 baby unicorns that can be removed through the zippered opening on mommy’s tummy. HUGGABLY PLUSH : Each of the narwhal stuffed animal is designed with snuggles and cuddles in mind so we use the softest and plushest materials to make them perfect for hugging and cuddling. UNICORN GIFTS FOR GIRLS: Makes a great Christmas or birthday gift for girls, these plush unicorn dolls for girls can be used for tea parties or story time. This soft and comforting unicorn family will become favorite companions for playtime and bedtime. NCLUDED IN SET : Our snuggable set of narwhal stuff for girls comes with; Mommy Narwhal with metallic horn and colorful unicorn aesthetic and four baby narwhals (two pink, blue and white narwhal girls) HOURS OF FUN : Mommy Narwhal plush and babies are the perfect bedtime buddies, traveling companions and stuffed plush toys for girls ages 3 4 5 6 7 8 years. Keep your little one's imagination entertained and teach them more about the unique narwhales. Toys & Games Preschool Pre-Kindergarten Toys Stuffed Animals & Toys

================================================================================
QUERY: Didn't hold my grandchildrens' interest.

BM25 top results:
1. (6.881) Funko POP Animation: My Hero Acadamia - Eri, Multicolor, (47594) Eri's quirk can be dangerous to others with quirks which led to her mother disowning her. Rescue Pop! Eri and bring her into your My Hero Academia collection to train her how to use her quirk safely. Vinyl figure is approximately 3.5-inches tall. Vinyl Imported Eri's quirk can be dangerous to others with quirks which led to her mother disowning her. Rescue Pop! Eri and bring her into your My Hero Academia collection to train her how to use her quirk safely . Vinyl figure is approximately 3.5-inches tall. Package Dimensions: 9.0 L x 16.4 H x 11.6 W (centimeters) Item Package Weight: 0.25 pounds Toys & Games Toy Figures & Playsets Action Figures
2. (5.131) Panda Toy for Girls 5 Pcs Set. Mommy, 2 Baby Panda Toys, XL Furry Bag and Baby Blanket. Cute Plush Gift Set 3 4 5 Year Old Girl, Stuffed Animal for Little Girls. Birthday, Christmas Age 3-8 PERFECTTO TOY DESIGN - Where perfection and design go hand in hand. This is Sharon from Perfectto I LOVE MY JOB! I’m a mother, so all my design choices get tested on my own family before I bring them to you and I’ve never seen my girls more excited than with this rabbit family set. SAFETY, QUALITY AND SUITABILITY ARE OUR FIRST CONCERNS We maintain strict standards of only the best quality materials for our plush toys. They are durable, washable and practical while still being sweet and adorable. NOT JUST ANOTHER STUFFED TOY Small stuffed animal toys for kids are fun but your kids need more. Cuddly Mommy Bunny and two babies plus the delightful little blankie bring your child lots of enjoyment and imaginary fun play. Among the most significant benefits of allowing a girl to play with stuffed animal toys are that it sparks their creativity. In reality, it enables their imagination to run rampant. THE PRACTICAL SIDE OF THIS TOY The shaggy white bag adds a practical element to this whole set. Large enough to carry Mommy and two babies, Great for use at home or away. Perfect to take on long trips in the car, on the bus, train, or plane. Your little one will love having all her precious plushies close to hand to while away the time. All this results in a much more pleasant and less stressful trip for child and parent. CHRISTMAS IS JUST AROUND THE CORNER and this is a great gift for your little princess from Mom and Dad, Grandma and Grandpa, aunts and uncles or friends. BUY YOURS WHILE STOCKS LAST, so you don’t have to hunt down your plush bunnies for Xmas. 5 PIECE PANDA TOY SET FOR GIRLS – Soft and fluffy, black and white mommy bear, 2 baby pandas, baby doll blanket and extra-large white furry purse/handbag - SO MUCH LARGER than any other pet bag. THE birthday gift for any little girl age 3-8 (4 5 6 7 year old girl gift), Christmas and birthdays. THE PERFECT PANDA SET GIFT FOR GIRLS – Meaningful role-play family set, teaches your child how to care and protect. Develops languages skills and cognitive ability along with compassion and kindness. Not just another panda, but a whole family to play and cuddle with. PANDA STUFFED ANIMAL TOY that your girl or boy will love. Our Panda family toy set bring mystery into the life of your toddler and they will love the hours of the imaginary play. They’ll especially enjoy wrapping baby panda up in their very own SOFT BLANKY. FOR YOUR PEACE OF MIND - All parts are USA Children Certified. Made of the best and softest fabrics. WE AIM FOR PERFECTION – We design our own unique play sets for little girls and boys like yours and we’re available to answer any concern you may have. Toys & Games Preschool Pre-Kindergarten Toys Stuffed Animals & Toys
3. (3.425) READY 2 LEARN Christmas Crafts - Design Your Own Travel Mugs - Set of 2 - Christmas Crafts for Kids - Reusable 11 oz Water Bottles - BPA Free Design your own holiday-themed Travel Mugs with this complete Christmas craft kit! This Christmas craft kit includes: 2 bottles, 2 blank insert sheets, 4 insert sheets featuring Christmas-themed designs to color and 2 detachable straps. Children will love to create unique Christmas-themed designs, decorate their water bottles and give customized gifts to the entire family! This water bottle craft kit fosters creative expression, hand-eye coordination and fine motor skills as children color or draw their own designs! || These reusable water bottles hold up to 11oz of liquid and are BPA-free. || For ages 3+. 2 CUSTOMIZABLE BOTTLES -- This water bottle craft kit includes 2 bottles, 2 blank insert sheets, 4 insert sheets featuring Christmas-themed designs for coloring, 2 detachable straps and illustrated instructions CREATIVITY TO GO! -- These water bottles are reusable and can hold up to 11 oz of liquid. Children will love to take their Christmas designs on the go! DESIGNED FOR KIDS -- These travel mugs are made of durable, BPA-free plastic. Simply decorate and color the designs, then twist open the inner enclosure and insert them. A clever Christmas craft idea! MAKE CUSTOMIZED GIFTS -- Children can create unique gifts and treasures for the entire family. Brother, sister, mom, dad and grandma will love to receive these personalized water bottles! FOSTER EARLY DEVELOPMENT -- Arts and crafts activities develop fine motor, identification and problem-solving skills in a fun, stress-free way. Help kids grow with this Christmas craft kit! CRAFT, IMAGINE, CREATE -- At READY 2 LEARN, we believe kids should play freely and immerse themselves in creativity! Our products are designed to inspire confidence and let imaginations run wild! Toys & Games Arts & Crafts Craft Kits Scrapbooking

Embedding search top results:
1. (1.354) Big Bubbles Dinosaur Bubble Machine for Kids Backyard Summer Toys for Outdoors Activity, Easter, Birthday Gift for Boys& Girls  Product Content: 1 x Bubbles Gun, 1 x 8oz Bubble Liquid. Not Included Screwdriver&Batteries. Perfect for Christmas gifts, birthday gift, party toys, Easter gift, Halloween gift, holiday toy gifts New Year Gifts for kids ages 3 4 5 6 7 8 9 10 year old boys/girls Refer to the installation steps or installation video in Figure 3: ① Unscrew the screws of the battery compartment cover. ② Put the battery in the correct way. ③ Install the protective cover and the fan blade (1mm gap is reserved at the fan blade installation place). ④ Test whether the operation is smooth. ⑤ For normal operation, install the battery compartment cover and other accessories and start playing Happy Time for Family - Child's and dogs like to chase colorful bubbles in the sun. The pictures of children and dogs playing make most adults and elderly people recall their happy childhood, as if they were children again. The cute dinosaur looks and solid touch are beloved by children alike, toddler kids easily create huge bubbles. With round appearance and high-quality materials, parents can rest assured to watch their children play or game together Happy Time for Kids - Perfect for Themed Party, Ceremony, Carnival, Birthday Parties, Party Favors, Camping Trips, Halloween, Weddings, School Classroom, Easter Basket Stuffers, Outdoor Water Toy Game Activities, Beach, Pack, Backyard Bubbles or Pool party etc..RUN BRAIN GO bubble gun brings fun and laughter to children & parents & pets Worry Free Purchase - The dinosaur bubble gun certified conforms to U.S toy safety standards ASTM. Rest assured to buy and play. We provide 7*24 hours Amazon Messages best service for your. Free exchange/return for any product quality issues to ensure your shopping experience Toys & Games Sports & Outdoor Play Bubbles Bubble Makers
2. (1.374) Wonder Forge Curious George Matching Game for Boys & Girls Age 3 and Up - A Fun & Fast Monkey Memory Game Product Description Play the classic game of matching and memory with everybody's favorite monkey! Flip over tiles and find colorful pictures of curious George and friends. Collect the most pairs to win! From the Manufacturer It’s the classic game of matching and memory—now featuring everybody’s favorite monkey. Flip over two tiles to find colorful pictures of Curious George and his friends. Did you find a match? If so, keep them in your scoring pile and take another turn. If not, turn them back over—but try to remember what pictures they had for later in the game. Collect the most pairs to win. I Can Do That. Games foster self-confidence by giving kids a chance to discover what they can do. Favorite Dr. Seuss, Curious George, and Richard Scarry characters come to life—challenging kids to run, slide, hide, seek, sort, explore—and more. By engaging kids physically, socially, and creatively, I Can Do That. Games provide endless hours of fun for the whole family. What you get – curious George matching game comes with 72 tiles and instructions. Clear instructions – Easy to learn with a clear instruction manual. Learn to play in less than five minutes! Develops critical skills – this game helps preschoolers practice their focus, memory, and matching skills. Characters you love – enjoy fun pictures of all your favorite curious George characters, including George, the man with the yellow hat, chef pisghetti, compass, Gnocchi, and more! Great for kids and families – matching not only offers great solo play opportunities for your preschooler, but is also a great game for adults to join in on the fun. It takes just 15 minutes to play, less than 5 minutes to teach, and makes a fantastic Easter gift! Toys & Games Games & Accessories Board Games
3. (1.376) LeapFrog 490403 Leap Pad Peppa Pig Cartridge Product Description Read & play with Peppa Pig! help Peppa and George play entertaining games as they tidy up the house together! find the objects to pick up and learn their beginning letters. You can also read about Peppa's fancy dress party through the interactive e-book and find out who wins the prize for the best outfit! there are also lots of interactive activities, such as spot the difference in George's dinosaur book. For ages 3-5 years. Works with all leap pad systems. Set Contains: 1 x Leap Pad Peppa Pig Cartridge, 1 x Instruction Manual 100% Help Peppa and George play entertaining games as they tidy up the house. Teaches alphabet, beginning letters, vocabulary, reading, and problem solving Ages 3-5 years Model number: 490403 Toys & Games Learning & Education Electronic Learning Toys Learning System Cartridges

================================================================================
QUERY: Five Stars

BM25 top results:
1. (3.815) Guardian Tabletop Gaming Backpack | Deluxe Portable Carrying Case with Space For 135+ Figurines, Large Miniatures, and Wargame Transportation | Includes Four Compartment Trays & 3 Layers of Pluck Foam  HAMMER OF WAR: The Guardian transport case features 135 compartments at 32mm x 54mm, spread across five foam trays PLUCK UP YOUR COURAGE: Customize your load-out with three 54mm deep pluck foam trays for big figures, vehicles, tanks, space ships, and dynamic sculpts SECURE THE PAYLOAD: Got some empty space? Secure your load with 3 tear-away securing shelves to keep your gear where it's supposed to be WE ARE LEGION: Whether a beginning gamer or a seasoned veteran, the Guardian can protect most popular wargames, including figurines from D&D, Games Workshop, Warhammer, and Star Wars X-Wing BELLS AND WHISTLES: The Guardian is made by gamers, and sports quality-of-life bonuses like a mesh pocket for rulebooks, a lock friendly zipper for added security, and freestanding plastic feet Toys & Games Collectible Toys Collectible Display & Storage Carrying Cases
2. (3.362) PixieCrush Narwhal Unique Stuffed Animals for Girls Ages 3 4 5 6 7 8 Years; Snugababies Stuffed Mommy Narwhal with 4 Baby Narwhals in her Tummy; Toy Plush Pillows for Girls  FIVE TOYS IN ONE : The stuffed mommy narwhal comes with a surprise in her belly, 4 baby unicorns that can be removed through the zippered opening on mommy’s tummy. HUGGABLY PLUSH : Each of the narwhal stuffed animal is designed with snuggles and cuddles in mind so we use the softest and plushest materials to make them perfect for hugging and cuddling. UNICORN GIFTS FOR GIRLS: Makes a great Christmas or birthday gift for girls, these plush unicorn dolls for girls can be used for tea parties or story time. This soft and comforting unicorn family will become favorite companions for playtime and bedtime. NCLUDED IN SET : Our snuggable set of narwhal stuff for girls comes with; Mommy Narwhal with metallic horn and colorful unicorn aesthetic and four baby narwhals (two pink, blue and white narwhal girls) HOURS OF FUN : Mommy Narwhal plush and babies are the perfect bedtime buddies, traveling companions and stuffed plush toys for girls ages 3 4 5 6 7 8 years. Keep your little one's imagination entertained and teach them more about the unique narwhales. Toys & Games Preschool Pre-Kindergarten Toys Stuffed Animals & Toys

In [25]:
with open("../data/processed/bm25_index.pkl", "wb") as i:
    pickle.dump(bm25, i)

with open("../data/processed/tokenized_products.pkl", "wb") as i:
    pickle.dump(tokenized_products, i)

In [26]:
faiss.write_index(index, "../data/processed/product_index.faiss")

<div class="alert alert-info">
    
### Step 4: Qualitative Evaluation
</div>

<div class="alert alert-info">
    
### Step 5: Web App
</div>