In [1]:
import pandas as pd
import numpy as np
from rank_bm25 import BM25Okapi
from langchain_community.retrievers import BM25Retriever
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import re
import pickle
from langchain_openai import OpenAIEmbeddings
import faiss
from pathlib import Path
import sys

In [2]:
PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
    
META_FILE   = PROJECT_ROOT / "data" / "raw" / "meta_Toys_and_Games.jsonl"
REVIEW_FILE = PROJECT_ROOT / "data" / "raw" / "Toys_and_Games.jsonl"

meta = pd.read_json(META_FILE, lines=True, nrows=100000)
review = pd.read_json(REVIEW_FILE, lines=True, nrows=100000)

<div class="alert alert-info">
    
### Step 1: Data Exploration and Preprocessing
</div>

In [3]:
review.dtypes

rating                        int64
title                           str
text                            str
images                       object
asin                            str
parent_asin                     str
user_id                         str
timestamp            datetime64[ms]
helpful_vote                  int64
verified_purchase              bool
dtype: object

In [4]:
meta.dtypes

main_category          str
title                  str
average_rating     float64
rating_number        int64
features            object
description         object
price              float64
images              object
videos              object
store                  str
categories          object
details             object
parent_asin            str
bought_together    float64
subtitle               str
author              object
dtype: object

In [5]:
cleaned_meta = meta.drop(columns = ['videos', 'price', 'images', 'bought_together', 'subtitle', 'author'])
cleaned_meta.head()

,main_category,title,average_rating,rating_number,features,description,store,categories,details,parent_asin
0,Toys & Games,"KUNGOON Happy Anniversary Balloon Banner,Weddi...",4.5,241,[],[],Kunggo,[],{'Package Dimensions': '10.12 x 8.03 x 0.51 in...,B08GPM7CQN
1,Toys & Games,Gothic Mothman Plushie Doll with Bright Red Ey...,1.3,2,[🦋 Mothman’s bright red eyes could stare you d...,[🦋 Description: Mothman’s bright red eyes coul...,Felicy,"[Toys & Games, Stuffed Animals & Plush Toys, P...","{'Item Weight': '2.47 ounces', 'Manufacturer r...",B09X9XW42H
2,Toys & Games,Melody Jane Dollhouse Builders DIY 1:24 Scale ...,4.2,67,[1:24 Scale - Plastic - Approximate cut out si...,[],Melody Jane Dolls Houses,"[Toys & Games, Dolls & Accessories, Dollhouse ...","{'Item Weight': '0.48 ounces', 'Manufacturer r...",B01I9QET6M
3,Toys & Games,Traxxas Stampede 4X4: 1/10 Scale 4wd Monster T...,4.5,48,[Waterproof electronics for all-weather drivin...,[Stampede 4X4 is built Traxxas Tough to withst...,Traxxas,"[Toys & Games, Remote & App Controlled Vehicle...",{'Product Dimensions': '15.63 x 13.39 x 8.94 i...,B019XEEX1A
4,Toys & Games,Hot Wheels Monster Truck 1:24 Scale 2022 Bone ...,4.8,17699,[Designed in 1:24 scale with durable die-cast ...,[The Hot Wheels Monster Trucks 1:24 scale die-...,Hot Wheels,"[Toys & Games, Preschool, Pre-Kindergarten Toys]",{'Product Dimensions': '5 x 6.27 x 5.5 inches'...,B09G7K3JWQ

In [6]:
reviews = review[review['verified_purchase'] == True]
cleaned_reviews = reviews.drop(columns = ['images', 'timestamp', 'user_id', 'verified_purchase'])
cleaned_reviews.head()

,rating,title,text,asin,parent_asin,helpful_vote
0,5,Granddaughters love them!,I purchased several of these for my granddaugh...,B09QH7QJS7,B09QH7QJS7,0
1,3,Arrived broken,"It’s cute, but it arrived broken & has some pr...",B06XYKSKQP,B06XYKSKQP,1
2,5,Dylan loves them!!!,Bough for my grandson Dylan. He loves them.,B07SFF3YQW,B07XRSD5R9,0
3,5,Janod quality and very cute...,This was great for my daughters circus themed ...,B007JWWUDW,B007JWWUDW,0
4,3,I used for my daughters circus birthday party ...,This is very cute but beware that the animals ...,B00MZG6OO8,B00MZG6OO8,2

In [7]:
parent_asin = list(pd.Series(np.intersect1d(cleaned_reviews['parent_asin'], cleaned_meta['parent_asin'])))

cleaned_reviews = cleaned_reviews[cleaned_reviews['parent_asin'].isin(parent_asin)]
cleaned_meta = cleaned_meta[cleaned_meta['parent_asin'].isin(parent_asin)]

In [8]:
cleaned_meta['description'] = cleaned_meta['description'].apply(
    lambda x: " ".join(x) if isinstance(x, list) else (x if isinstance(x, str) else "")
)
cleaned_meta['description']

0
4        The Hot Wheels Monster Trucks 1:24 scale die-c...
9                     Tamiya 1/35 Brick Wall Set, TAM35028
21                    LEGO Minifigures Series 11 Scarecrow
30       Guardhouse heavy duty coin boxs are crafted of...
                               ...
99941    Our new full body, performance quality, ventri...
99945
99952    From teaching first words to encouraging first...
99973    This soft, cuddly bunny figure wants to belong...
99985    Barbie doll and her cake decorating playset ar...
Name: description, Length: 7435, dtype: str

In [9]:
cleaned_meta['details'] = cleaned_meta['details'].apply(
    lambda x: " ".join([f"{k} {v}" for k, v in x.items()]) if isinstance(x, dict) else ""
)
cleaned_meta['details']

0        Package Dimensions 10.12 x 8.03 x 0.51 inches ...
4        Product Dimensions 5 x 6.27 x 5.5 inches Item ...
9        Brand TAMIYA Age Range (Description) Kid Theme...
21       Product Dimensions 0.5 x 0.5 x 1 inches Item W...
30       Brand Guardhouse Material Engineered Wood Prod...
                               ...
99941    Product Dimensions 25 x 12 x 10 inches Item mo...
99945    Material Polyester Brand Jay Franco Style Mode...
99952    Product Dimensions 21.26 x 16.69 x 18.11 inche...
99973    Product Dimensions 7.87 x 8.66 x 8.27 inches I...
99985    Product Dimensions 3 x 15.5 x 12.75 inches Ite...
Name: details, Length: 7435, dtype: str

In [10]:
cleaned_meta['features'] = cleaned_meta['features'].apply(
    lambda x: " ".join(x) if isinstance(x, list) else ""
)
cleaned_meta['features']

0
4        Designed in 1:24 scale with durable die-cast m...
9        This plastic model kit requires plastic cement...
21                                Packaged in zip lock bag
30       This chipboard box stores up to 24 proof sets ...
                               ...
99941    High quality full body ventriloquist style pup...
99945                                            Polyester
99952    Interactive baby walker and learning toy with ...
99973    Having your own bunny figure to love is the be...
99985    Barbie baker doll comes with a sweet playset t...
Name: features, Length: 7435, dtype: str

In [11]:
cleaned_meta['categories'] = cleaned_meta['categories'].apply(
    lambda x: " ".join(x) if isinstance(x, list) else ""
)
cleaned_meta['categories']

0
4             Toys & Games Preschool Pre-Kindergarten Toys
9
21                      Toys & Games Building Toys Figures
30
                               ...
99941               Toys & Games Puppets & Puppet Theaters
99945
99952    Toys & Games Preschool Toddler Toys Push & Pul...
99973       Toys & Games Kids' Electronics Electronic Pets
99985            Toys & Games Dolls & Accessories Playsets
Name: categories, Length: 7435, dtype: str

##### Description of text preprocessing decisions
To prepare the data, some preprocessing steps were taken in order to ensure there is consistency and usability of textual fields.
First, only relevant and needed columns were kept from both datasets. From the metadata, we only kept columns such as `title`, `features`, `description`, and `categories`, while other columns that were less informative and noisy were removed. These removed columns ranged from `images` to `videos` and `prices`.

As the next step, the two datasets were aligned by filtering on the intersection of the `parent_asin` to make sure that only the products that appear in both datasets are included.

Furthermore, due to the inconsistency of the text fields, normalization was required. Specifically, the `description` column sometimes appeared as a list or dictionary, so flattening it into a single string was the appropriate step.
The `features` column, originally a list, was converted into a string separated by space. Lastly, the `details` column, which was a dictionary, was turned into a string by joining them via key–value pairs.

Through these EDA steps, the text information in the dataset became consistent, flat strings that were more suitable for the tokenization and other things that are going to take place in BM25 and embedding-based search.

<div class="alert alert-info">
    
### Step 2 and 3: BM25 Search and Semantic Search
</div>

In [ ]:
# code adapted from lecture 5

# combining all the important and useful columns from the meta dataset
products = (
    cleaned_meta['title'].fillna('') + ' ' +
    cleaned_meta['description'].fillna('') + ' ' +
    cleaned_meta['features'].fillna('') + ' ' +
    cleaned_meta['categories'].fillna('')
)
products = products.tolist()
queries = cleaned_reviews['title'].tolist()

def simple_tokenize(text):
    """Tokenization by lowercasing, stripping non-alphanumeric characters, 
    and splitting text into tokens."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    return text.split()

tokenized_products = [simple_tokenize(p) for p in products]
bm25 = BM25Okapi(tokenized_products)

model = SentenceTransformer("all-MiniLM-L6-v2")
product_embeddings = model.encode(products).astype("float32")

# using faiss to index product embeddings for semantic search
index = faiss.IndexFlatL2(product_embeddings.shape[1])
index.add(product_embeddings)

def bm25_search(query, top_k=3):
    """Return the top-k products ranked by BM25 relevance score for a given query."""
    tokenized_query = simple_tokenize(query)
    scores = bm25.get_scores(tokenized_query)
    ranked_idx = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:top_k]
    return [(products[i], scores[i]) for i in ranked_idx]

def embedding_search(query, top_k=3):
    """Retrieve the top-k products by semantic similarity using FAISS vector search."""
    query_embedding = model.encode([query]).astype("float32")
    distances, indices = index.search(query_embedding, top_k)
    return [(products[i], distances[0][rank]) for rank, i in enumerate(indices[0])]

for q in queries[:2]:
    print("=" * 80)
    print(f"QUERY: {q}\n")

    print("BM25 top results:")
    for rank, (product, score) in enumerate(bm25_search(q), start=1):
        print(f"{rank}. ({score:.3f}) {product}")

    print("\nEmbedding search top results:")
    for rank, (product, score) in enumerate(embedding_search(q), start=1):
        print(f"{rank}. ({score:.3f}) {product}")
    print()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

================================================================================
QUERY: super cute. my 4 year old loves

BM25 top results:
1. (14.056) TOP BRIGHT Toddler Fishing Game for 2 Year Old, Kids Fishing Games for 2 Year Olds, Toddler Birthday Gift for Two Year Old Boy Girl  COGNITIVE DEVELOPMENT TOYS: Let your child enjoy hours of fun with the TOP BRIGHT toddler fishing game. The fishing game for 2 year old includes 26 wooden fish puzzles which are patterned with alphabet, numbers and cute ocean creatures, making it a great teaching tool to develop their hand and eye coordination as well as their motor skills. It’s never too early to begin STEM educational techniques HOW TO PLAY: The aim of the fishing game is to catch 26 wooden fish with the aide of magnetic rods. Your kids can play with an adult or a friend as they follow their natural instinct and explore the fun of a pretend play game whilst learning to play fairly and share. Playing with someone else also develops their social skills which makes it a must have two year old boy gifts BRIGHT, COLORFUL AND FUN: The games for 2 year olds are made from high quality, natural solid wood and are coated with environmentally friendly water-based paint. It is completely non-toxic and safe as to play without the risk of harm as all edges have been made smooth with no rough surfaces CATCH AND COUNT: The toddler birthday gift is all about fun and educational, which is why we have developed this 2 year old boy birthday gift to enhance their number skills. There are different numbers on each fish puzzle. Go fishing, then add the numbers on them. Kid who has higher result wins! GIFTS FOR 2 YEAR OLD: The perfect fishing game for 2 year old who just loves to learn whilst playing. Our kids fishing game has been built to last and will provide years of fun. Our toddler birthday gift with robust design can be played indoors and outdoors and are great for children’s parties and play dates Toys & Games Dress Up & Pretend Play Magnetic & Felt Playboards
2. (13.804) Toys for 3 4 5 Year Old Boys, Remote Control Car for Toddler Age 3-5, Mini RC Truck Toys for 3 4 Year Old Kids, Small Car Toys for Boys 3-5 Gifts for 3 4 5 Year Old Boys Girls Birthday  🚗【ABS High-quality】The remote control car toys for 3 4 5 year old boys is made of non-toxic, high-quality ABS plastic material, does not irritate the skin and is safe for kids. Premium quality durable rc car toy age 3-5 provides children better and more healthy companionship while playing, satisfy the super experience of your child's imagination. With these toy cars, your kids are able to build a racing game to gain more fun in the playing time. 🚗【Remote Control Car for 3-5 Year Old】This car toys for 3 4 5 6 7 year old is made of high-quality ABS plastic, rounded edge design, prevent children from potential injury. The remote control car helps kids to explore the field of automotive technology, developing kid's intelligence and practicing ability, improving children's hand-eye coordination. The toddler remote control car is a good choice for your kids to race with friends and share happy times with family. 🚗【RC Car Easy to Control】This rc car for 3 4 5 year old kids have 4 channel drive can go forward, backward, turn left, turn right, front wheel unit guarantees accurate route direction.A great educational learning toy for 3 4 5 year old that can improve children's reaction ability and inspire the child's interest. Be Noted that turning left/right requires forward/backward power to drive at the same time. 🚗【Perfect Size Car Toys】The mini RC car toys for 3 4 5 year old boys is easy enough for toddler age 3-5 to bring it anywhere to play. This RC vehicle is lightweight and the size of car is 2.9 x 2.5 x 4.8 inch is portable to store and carry along. Your kids can play anywhere and anytime they like. Remote control car toy need 4*1.5v AA batteries, 2 for remote controller and 2 for RC car (Not included). 🚗【Ideal Gifts for Kids】The toys for 3 4 5 year old boys are perfect gifts for Halloween, Christmas and other holidays. It is a perfect Gift for 3-5 year old boys and girls with playful car, fits for family fun time; Kids companion, keeps kids engaged and entertained and offers a fun and educational way to play. Toys & Games Preschool Pre-Kindergarten Toys Activity Cars, Trucks, Boats & Planes
3. (13.802) LODBY Dinosaur Trucks Toys for Kids 3-5 Year Old Boys, Friction Powered Dino Vehicles Toys for Age 3-5 Year Old Boys Birthday Gifts, Dinosaur Car Train for Kids Outdoor Toys for Toddlers Boy Age 2-6  🦕 Trucks Playsets （2 Pack) -- Dinosaurs are coming, your kid's dinosaur convoy team is ready to go! This item is a race truck sets, which include 2 cool dinosaur trucks (horned dragon, tyrannosaurus Rex). 🦕 【Super Pull Back Design】- Double pull back design, Battery free, everything is under your hands. As long as you give me strength, the dinosaur team will always serve your child. Whether in the living room, park, lawn or garden, the dinosaur team will be with your child. 🦕 【A Special Stunt】- Hi, little guy, look at my cool 360 rotation stunt. Just give “me” some strength, push “me” forward and then stand “me” up, my stunt will be shown to you. 🦕 【GO! Dinosaur Truck Team】- The race game is ready to start, which one do you choose? horned dragon or tyrannosaurus Rex? Bring your dinosaur truck team to release the passion with your friends or family. 🦕 【Surprise for Child】- Baby, are you ready? Your most anticipated gift will arrive soon. Dinosaur truck team, is one of the most anticipated gifts and prizes for your child, whatever birthday gifts, holiday gifts, Christmas gifts, Thanksgiving gifts. Toys & Games Preschool Pre-Kindergarten Toys

Embedding search top results:
1. (1.046) JC Toys Lil Cutesies 8.5" All Vinyl Baby Doll | Posable and Washable | Removable Outfit | Lulu- Blue Eyes Ages 2+ You are about to enter the magical world of Lil’ Cutesies! an exclusive collection of fun-loving baby dolls with adorable expressions. Each doll is designed with its own personality and its own cute look. Meet Mimi, she is brown-eyed and pouty, but don’t let her looks fool you. She is fun-loving and very artistic. Her BFF Bibi has green eyes and loves to read! Bibi is also the only friend that has two cute little teeth! Lulu is the one with twinkly blue eyes that are not as big as her sweet tooth! she loves cookies!!! Let’s not forget about Super sweet Lila! she has a big heart that matches her big brown eyes and loves hugs! your new Lil' Cutesies doll is sure to be a great addition to your child's doll collection! she has an all-vinyl design that makes it a breeze to keep clean. Even if a mishap occurs, you just need to wipe her down to make her as good as new again! she's decked out in adorable Lil' Cutesies Purple Doll clothes. Your little one will love changing her clothes and playing with her baby doll. This adorable Lil' Cutesies doll also has movable legs and arms, and her head is movable as well. Your child will never get tired of playing with her and will be able to position her in countless ways. You'll love this baby doll too because JC Toys offers it for a remarkably low everyday price. Don't forget to look for all of the available Lil' Cutesies Accessories, swings, tricycles, buggies, baths, collect them all!!!! COLLECTABLE // Collect all the different expressions and combine them with the available Lil' Cutesies Accessories. Lil' Cutesies, Lots of Fun! SAFETY TESTED AND APPROVED // Made with non-scented, BPA free, safety tested vinyl. Soft & smooth to the touch yet durable for years. TEACHES CHILDREN NURTURING SKILLS // Her soft & cuddly body promotes holding, cuddling and special care. She is the perfect size for children to hug and love. MADE BY JC TOYS // A USA Family run, award-winning baby doll designer and producer with over 30 years experience creating real-life baby dolls. Proudly designed by Berenguer. Toys & Games Preschool Pre-Kindergarten Toys Activity Dolls & Dollhouses
2. (1.064) Click N' Play Toy Kitten Set for Kids, Toy Cat Bed - Little Girl Toys, Toys for 3+ Year Old Girls, Gifts for 3+ Year Old Girl, Gifts for 3 Year Old Girl, Toys for 3 Year Old Girls, Girl Toys Age 4-5 Have this cute cuddly kitten adopted by your doll. This set includes all you need for keeping your kitten busy and comfortable. Your doll could also carry her kitten along wherever she goes in the adorable ventilated carrier. She can keep her kitten active while chasing mice, and staying still being brushed. At supper time, your doll can prepare the kitten's nutritious meal in the dog bowl and serve it to him. Then, when it's time to go to sleep, the kitten can snuggle with his blanket in his soft, padded bed. GREAT GIFTS FOR 3+ YEAR OLD GIRL OR BOY: The Click N' Play toy kitten is cuddly and adorable. It's a great pretend play set for toddlers and kids (3-6 years old). It is definitely the perfect toy and a wonderful gift for kids who love cats on birthdays, holidays, and any other special occasion. It's an especially wonderful gift for 3 year old girl. ENCOURAGE IMAGINATION and ROLE-PLAYING FUN: Click N' Play provides a wide range of toy cats that help children play, practice and improve their pretend playing skills. This kitten toys set is not only adorable but also has plush texture, making it easy to cuddle with. This is a great 3 year old girl toys set that encourages imaginative play by encouraging children to pretend to feed, play with and train their little kitten. FASHIONABLE AND PORTABLE SET: This cuddly kitten and carrier toy will keep your child entertained for hours. Kids can easily transport this adorable kitten wherever they go thanks to the cute pink carrier with a carrying handle and zippered closure. They can have company whenever they want. If you're looking for gifts for 3 year old girl, you have come to the right place! 9 PIECE SET FOR HOURS OF FUN: The cat doll set comes with accessories that will bring hours of fun including a kitten doll, cat carrier, a toy cat bed and blanket, toy cat leash, tennis ball, bone, food bowl and cat doll brush. This set screams fun toys for 3 year old girls. A PERFECT COMPANION TO 18" DOLLS: Our play cat will make the perfect companion to 18 inches dolls of any style. The play kitten is 7" tall, and the carrier is 8 long x 5 wide x 6 tall. We would recommend this if you're looking for 3 year old girl gifts Toys & Games Preschool Pre-Kindergarten Toys Pretend Play Toy Figure Playsets
3. (1.117) Madame Alexander Sweet Smiles, Pink 20210 - 14” Sweet Smiles – Pink . This adorable 14” baby is just the right size for your child to snuggle . Baby has a soft body, a weighted bottom and molded head, legs, and arms so it feels so real to your child . Baby’s gently smiling face has sleep eyes, facilitating bedtime play. Dressed in an adorable bunny tee, polka dot leggings and matching cap. Engage your child in imaginative, nurturing play with this doll, teaching kindness and empathy. Doll wipes clean with damp cloth. Shipped in a window box. Includes bottle.Recommended for 12 months and up. Features light skin and blue eyes; soft body and molded arms and legs. Sweet Smiles: This adorable 14 inch baby has a soft body, a weighted bottom and molded head, legs, and arms so it feels so real to your child; Baby’s gently smiling face has sleep eyes; Ages 12 months plus Details: Dressed in an adorable bunny tee, polka dot leggings and matching cap; Features light skin and blue eyes and includes bottle; Shipped in a window box; Doll wipes clean with damp cloth Love Is In The Details: Our baby dolls are made to be played with safely and comfortably, with soft bodies and nontoxic materials. Realistic details like soft eye lashes are crafted to delight Empowering Girls: Kids' toys like the lifelike dolls we offer inspire creativity, nurturing, and kindness; Madame Alexander offers every child a perfect baby doll of their own Made with Love in the Details: With nearly 100 years of toymaking innovation, Madame Alexander's mission is to create quality dolls that deliver invaluable play experiences and inspire passion in collectors Toys & Games Preschool Pre-Kindergarten Toys Activity Dolls & Dollhouses

================================================================================
QUERY: super fun but be VERY CAREFUL>

BM25 top results:
1. (15.373) Fire Fox EPO Foam Super Durable 21.75" Hand Glider , White Firefox hand glider is perfect for the back yard, front yard and parks. It will glide for over 75 feet. Made of EPO foam, which is very flexible, makes it almost indestructible. Careful use should yield hours and hours of flying fun. No Glue or Tape required. Wingspan 22.75". Made from EPO Foam Glides 75 Feet Wingspan 21.75" Firefox hand glider is perfect for the back yard, front yard and parks It will glide for over 75 feet Made of EPO foam, which is very flexible, makes it almost indestructible Careful use should yield hours and hours of flying fun No Glue or Tape Required Toys & Games Novelty & Gag Toys Flying Toys Airplane Construction Kits
2. (11.610) smttw Wooden Sorting & Stacking Toys for 1-3 Toddlers, Montessori Toys Educational Shape Sorter Color Recognition Toys for Boys Girls, Preschool Kids Learning Puzzle Gift(4 Shapes 20 Pieces)  Entertainment & Education: This wooden sorting&stacking toy is unique and especially designed for Toddlers. It containers 20 pieces which including 4 different geometric shapes and up to 20 colors. 5 color scale from light to dark, small to large which helps to build early color, shape and size differentiation skills. Shape & Color Recognition: Toddlers' time is the best point to exercise children’s minds.This funny montessori toy is perfect for kids to learn color recognition and geometric sorting. Kids can sort by shape, by color which is helpful to build attention & patience, hand-eye coordination ability. Especially for Children: Unique & Careful design size for children which is perfect for kids to hold. Large than normal one. Smooth edges can also protect your kids’ hands very well. It is very attractive to your kids for its bright to dark colors and different geometric shapes. Perfect gift for 1-3 year old toddlers. High Quality Guarantee: We do care on kids’ products and insist on adopting super quality and safe material. This wooden sorting&stacking toy is made of 100% non-toxic wood and eco-friendly print. The edge is polished carefully to care about kids and the paint is durable. Best Choice as Gift: Montessori toy can always be the great present for your kids. What it brings is not only the educational stuff for your children, but also the happiness that around parents family with your kids. Take part in every important moment with your kids. Toys & Games Baby & Toddler Toys Early Development & Activity Toys Sorting & Stacking Toys
3. (10.675) Maomoto Cabbage Dog Plush Toys Vegetable Dog Toy, 15.7" Cabbage Shiba Inu Corgi Akita Dog Stuffed Figure, Cute Vegetables Dog Hugging Pillow, Soft Toy Children's Gift Decorations  ❤【Soft Touching】: The cute Cabbage Dog stuffed doll has an fat body, cute expression, very cute, super soft. ❤【Dimensions】: Size of Cabbage Dog: 15.7inch / 40cm. ❤【 Great plush toy friend】: Vegetables Dog Hugging Pillow is made of fine soft plush and high grade PP cotton. So super soft, comfortable, fluffy and elastic. It is very suitable for cuddling. ❤【Unique gift】:Perfect gifts for your children, lovers, friends, etc. This is not only a plush toy, but also a body pillow, which can be placed anywhere you want, such as on the bed, on the sofa, in the car, on the chair, in the children's room, and so on. ❤Suitable for children over 3 years old.It looks like cabbage, but in fact it is also a cute puppy, I am sure your child will love this unique gift as a new friend！ Toys & Games Stuffed Animals & Plush Toys Plush Pillows

Embedding search top results:
1. (1.144) Spot It! Halloween From the Manufacturer Treat yourself to a game of Spot it. Halloween, but don't be tricked by the ingenious game mechanics. The award-winning game, Spot it. bewitches everyone with its fast-paced fun. Spot it. is truly a one-of-a-kind card game. Each card has 8 images of varying sizes. There is always one and only one, matching image between any 2 cards. There are 5 challenging mini-games packed into this tin. Depending on the mini-game, players simultaneously try to gain or get rid of their cards by spotting matches between 2 or 3 cards. Play your way through all the variations or just play your favorites. No matter how you play, Spot it. Halloween provides spirited competition and endless laughs. Spot it! has been bewitched with spooky symbols like jack-o'-lanterns, cobwebs, spell books, and zombies. There is always one and only one matching symbol between any two cards. Spot it fast to win! The perfect game for Halloween parties and post trick or treating fun! Develops visual perception skills, attention, and fine motor skills. A fast paced matching game for 2 to 8 players, ages 7 and up. Toys & Games Games & Accessories Card Games
2. (1.149) Who Can Do It - Compete with Your Friends to Win These Challenges [A Party Game] WHO CAN DO IT.[A Party Game] includes 250 action cards to see who in the group can do it! Compete against your friends to see WHO CAN swear in a foreign language, take the worst selfie and more 250 action cards to challenge your friends to see WHO CAN DO IT... Compete against your friends to swear in a foreign language, take the worst selfie or pretend to ride a mechanical bull Do the challenge first or best to win By the creators of the adult party game “DRUNK STONED OR STUPID” For 3+ players ages 17+ Toys & Games Games & Accessories Card Games Dedicated Deck Card Games
3. (1.199) TeeTurtle Here to Slay Base Game - from The Creators of Unstable Unicorns - A Strategic Card Game for Teens and Adults , Black A strategic card game. A role-playing adventure. A dangerous new world. Here To Slay is a fast-paced, easy to learn game that is perfect for all skill levels, whether you’re just entering the world of role-playing games or honing your masterful skills. The game was one of Kickstarter’s top 50 most backed projects of all time and is one of Pop Insider’s best geeky gifts of 2020! A strategic card game. A role-playing adventure. A dangerous new world. Here to slay is a fast-paced, easy to learn game that is perfect for all skill levels, whether you’re just entering the world of role-playing games or honing your masterful skills. The game was one of Kickstarter’s top 50 most backed projects of all time! From the creators of Unstable Unicorns, this brutal and adorable game takes 30-60 minutes to play and is for 2-6 players (recommended for ages 10+). The box contains 1 standard deck of 115 cards, 6 Party Leader cards, 15 oversized Monster cards, 2 six-sided dice, and 6 rules reference cards. Here to Slay makes a great gift for any game lover, and is one of Pop Insider’s best geeky gifts of 2020! Toys & Games Games & Accessories Card Games Dedicated Deck Card Games

In [13]:
bm25_PATH = PROJECT_ROOT / "data" / "processed" / "bm25_index.pkl"
with open(bm25_PATH, "wb") as i:
    pickle.dump(bm25, i)

tokenized_products_PATH = PROJECT_ROOT / "data" / "processed" / "tokenized_products.pkl"
with open(tokenized_products_PATH, "wb") as i:
    pickle.dump(tokenized_products, i)

In [14]:
product_index_PATH = PROJECT_ROOT / "data" / "processed" / "product_index.faiss"
faiss.write_index(index, str(product_index_PATH))

<div class="alert alert-info">
    
### Step 4: Qualitative Evaluation
</div>

In [15]:
query_set = {
    "keyword-based": [
        "Christmas toys for kids",
        "Action games for boys",
        "16 oz bottle"
    ],
    "semantic-based": [
        "Toys for kids at least 5 years old",
        "Games that boost children's creativity",
        "Toy or game for kids who love animals"
    ],
    "complex": [
        "Games that are straightforward to learn",
        "Sturdy and durable toys that can last long",
        "Games that are not easy for kids to become addicted",
        "Toys that can be played with a dog"
    ]
}

In [16]:
for key, val in query_set.items():
    for query in val:
        print("=" * 80)
        print(f"QUERY: {query} ({key}) \n")

        print("BM25 top 5 results:")
        for rank, (product, score) in enumerate(bm25_search(q, top_k=5), 
                                                start=1):
            print(f"{rank}. ({score:.3f}) {product}")

        print("\nEmbedding search top 5 results:")
        for rank, (product, score) in enumerate(embedding_search(q, top_k=5), 
                                                start=1):
            print(f"{rank}. ({score:.3f}) {product}")
        print()

================================================================================
QUERY: Christmas toys for kids (keyword-based)

BM25 top 5 results:
1. (15.373) Fire Fox EPO Foam Super Durable 21.75" Hand Glider , White Firefox hand glider is perfect for the back yard, front yard and parks. It will glide for over 75 feet. Made of EPO foam, which is very flexible, makes it almost indestructible. Careful use should yield hours and hours of flying fun. No Glue or Tape required. Wingspan 22.75". Made from EPO Foam Glides 75 Feet Wingspan 21.75" Firefox hand glider is perfect for the back yard, front yard and parks It will glide for over 75 feet Made of EPO foam, which is very flexible, makes it almost indestructible Careful use should yield hours and hours of flying fun No Glue or Tape Required Toys & Games Novelty & Gag Toys Flying Toys Airplane Construction Kits
2. (11.610) smttw Wooden Sorting & Stacking Toys for 1-3 Toddlers, Montessori Toys Educational Shape Sorter Color Recognition Toys for Boys Girls, Preschool Kids Learning Puzzle Gift(4 Shapes 20 Pieces)  Entertainment & Education: This wooden sorting&stacking toy is unique and especially designed for Toddlers. It containers 20 pieces which including 4 different geometric shapes and up to 20 colors. 5 color scale from light to dark, small to large which helps to build early color, shape and size differentiation skills. Shape & Color Recognition: Toddlers' time is the best point to exercise children’s minds.This funny montessori toy is perfect for kids to learn color recognition and geometric sorting. Kids can sort by shape, by color which is helpful to build attention & patience, hand-eye coordination ability. Especially for Children: Unique & Careful design size for children which is perfect for kids to hold. Large than normal one. Smooth edges can also protect your kids’ hands very well. It is very attractive to your kids for its bright to dark colors and different geometric shapes. Perfect gift for 1-3 year old toddlers. High Quality Guarantee: We do care on kids’ products and insist on adopting super quality and safe material. This wooden sorting&stacking toy is made of 100% non-toxic wood and eco-friendly print. The edge is polished carefully to care about kids and the paint is durable. Best Choice as Gift: Montessori toy can always be the great present for your kids. What it brings is not only the educational stuff for your children, but also the happiness that around parents family with your kids. Take part in every important moment with your kids. Toys & Games Baby & Toddler Toys Early Development & Activity Toys Sorting & Stacking Toys
3. (10.675) Maomoto Cabbage Dog Plush Toys Vegetable Dog Toy, 15.7" Cabbage Shiba Inu Corgi Akita Dog Stuffed Figure, Cute Vegetables Dog Hugging Pillow, Soft Toy Children's Gift Decorations  ❤【Soft Touching】: The cute Cabbage Dog stuffed doll has an fat body, cute expression, very cute, super soft. ❤【Dimensions】: Size of Cabbage Dog: 15.7inch / 40cm. ❤【 Great plush toy friend】: Vegetables Dog Hugging Pillow is made of fine soft plush and high grade PP cotton. So super soft, comfortable, fluffy and elastic. It is very suitable for cuddling. ❤【Unique gift】:Perfect gifts for your children, lovers, friends, etc. This is not only a plush toy, but also a body pillow, which can be placed anywhere you want, such as on the bed, on the sofa, in the car, on the chair, in the children's room, and so on. ❤Suitable for children over 3 years old.It looks like cabbage, but in fact it is also a cute puppy, I am sure your child will love this unique gift as a new friend！ Toys & Games Stuffed Animals & Plush Toys Plush Pillows
4. (10.508) KINGOU Wooden Puzzle Magic Ball Brain Teasers Toy Intelligence Game Sphere Puzzles for Adults/Kids  Name: Wooden Sphere Puzzle. Please note the size: 2.36 x 2.36 x 2.36 (inch) ★KINGOU is a registered brand, the trademark number is 5034717★ Children should be used under adult supervision. It is a puzzle that will entertain and challenge all of yours Hard to take it apart, but harder to assemble. Difficulty Rated: ★★★★☆ When assembling requires careful observation and thinking, analyze its internal structure.Our mind puzzle help to exercise brain, develop intelligence, improve problem-solving ability, and also relieve pressure Tips: paper instructions and video link QR code is prepared, but in order to make it challenging and fun, we suggest you try your best to unlock this wooden ball puzzle without instruction Toys & Games Puzzles Brain Teasers Assembly & Disentanglement Puzzles
5. (10.415) QINGQIU 12 Pack Colorful Slime Eggs Toys Easter Eggs for Kids Girls Boys Easter Basket Stuffers Fillers Gifts Party Favors QINGQIU 12 Pack Colorful Slime Easter Eggs Features: 1. It's very preferential to get 12 slime easter eggs for the price, super value, order it now. 2. What a beautiful color! Get the various colors slime eggs at the party, get all the attention, share your fun with others. 3. Colorful and ranibow, not big or small, play funny, the colorful slime eggs are very suitable as an easter gift for kids boys girls easter basket stuffers. 4. Our slime is made of environmental protection material, tested safe and non-toxic, high quality, please feel free to play, but not for kids under 3 years.  Specification: Color: as the picture showed Weight: 2.3oz/egg Size: 5x6.5cm (1.97"x2.56") Package: 12 slime eggs in a box  Note: Due to temperature effects, it may not be stretchy. Soak it in hot water at 40℃ before using. After playing, put the slime back into box, can maintain softness. Don't bake! Don't eat! Only for kids 3+ Super Value - It's very preferential to get 12 slime easter eggs for the price, super value, order it now Bright Colors - What a beautiful color! Get the various colors slime eggs at the party, get all the attention, share your fun with others Slime Egg Toys - Colorful and rainbow, not big or small, play funny, the colorful slime eggs are very suitable as an easter gift for kids boys girls easter basket stuffers High Quality and Safe - Our slime is made of environmental protection material, tested safe and non-toxic, high quality, please feel free to play, but not for kids under 3 years Perfect Gift - The 12 pack colorful slime eggs are perfect for kids boys girls, easter basket stuffers, easter gifts, easter basket fillers, party favors, party supplies, stocking stuffers, christmas stockings, christmas gifts, school classroom rewards, carnival prizes, pinata, goodie bags and more Toys & Games Novelty & Gag Toys Slime & Putty Toys

Embedding search top 5 results:
1. (1.144) Spot It! Halloween From the Manufacturer Treat yourself to a game of Spot it. Halloween, but don't be tricked by the ingenious game mechanics. The award-winning game, Spot it. bewitches everyone with its fast-paced fun. Spot it. is truly a one-of-a-kind card game. Each card has 8 images of varying sizes. There is always one and only one, matching image between any 2 cards. There are 5 challenging mini-games packed into this tin. Depending on the mini-game, players simultaneously try to gain or get rid of their cards by spotting matches between 2 or 3 cards. Play your way through all the variations or just play your favorites. No matter how you play, Spot it. Halloween provides spirited competition and endless laughs. Spot it! has been bewitched with spooky symbols like jack-o'-lanterns, cobwebs, spell books, and zombies. There is always one and only one matching symbol between any two cards. Spot it fast to win! The perfect game for Halloween parties and post trick or treating fun! Develops visual perception skills, attention, and fine motor skills. A fast paced matching game for 2 to 8 players, ages 7 and up. Toys & Games Games & Accessories Card Games
2. (1.149) Who Can Do It - Compete with Your Friends to Win These Challenges [A Party Game] WHO CAN DO IT.[A Party Game] includes 250 action cards to see who in the group can do it! Compete against your friends to see WHO CAN swear in a foreign language, take the worst selfie and more 250 action cards to challenge your friends to see WHO CAN DO IT... Compete against your friends to swear in a foreign language, take the worst selfie or pretend to ride a mechanical bull Do the challenge first or best to win By the creators of the adult party game “DRUNK STONED OR STUPID” For 3+ players ages 17+ Toys & Games Games & Accessories Card Games Dedicated Deck Card Games
3. (1.199) TeeTurtle Here to Slay Base Game - from The Creators of Unstable Unicorns - A Strategic Card Game for Teens and Adults , Black A strategic card game. A role-playing adventure. A dangerous new world. Here To Slay is a fast-paced, easy to learn game that is perfect for all skill levels, whether you’re just entering the world of role-playing games or honing your masterful skills. The game was one of Kickstarter’s top 50 most backed projects of all time and is one of Pop Insider’s best geeky gifts of 2020! A strategic card game. A role-playing adventure. A dangerous new world. Here to slay is a fast-paced, easy to learn game that is perfect for all skill levels, whether you’re just entering the world of role-playing games or honing your masterful skills. The game was one of Kickstarter’s top 50 most backed projects of all time! From the creators of Unstable Unicorns, this brutal and adorable game takes 30-60 minutes to play and is for 2-6 players (recommended for ages 10+). The box contains 1 standard deck of 115 cards, 6 Party Leader cards, 15 oversized Monster cards, 2 six-sided dice, and 6 rules reference cards. Here to Slay makes a great gift for any game lover, and is one of Pop Insider’s best geeky gifts of 2020! Toys & Games Games & Accessories Card Games Dedicated Deck Card Games
4. (1.245) Do You Really Know Your Family? A Fun Family Game Filled with Conversation Starters and Challenges - Great for Kids, Teens and Adults  Get ready for the best family game night as you laugh and learn new things about each other with this fun card game. See who really knows the family best as you answer fun questions about each other while sparking interesting conversations. Create hilarious family memories as you compete and perform silly challenges together. Super easy to learn and play - a perfect game for families with kids 8 and up, teens and adults. Toys & Games Games & Accessories Card Games Dedicated Deck Card Games
5. (1.256) Calliope Games Roll For It! - Red Edition  LIGHTHEARTED FUN: It’s fun, fast, and easy! Roll colorful dice, match them to target cards, and be the first hit 40 points to win! It's an instant classic game of dice rolling and decision making. PORTABLE FAMILY GAME: Play at home, in the car, in the park, anywhere! A box of cards and dice is all you need for a quick game! Roll the dice right into the box lid to play on the go! EASY TO LEARN: Learning a game has never been simpler. Roll the dice, match them to cards on the table, and win points. But watch out for canny players looking to steal the card you are after! A GAME OF CHANCE AND QUICK DECISIONS: Take turns choosing your best options as you race to collect 40 points by matching cards to your dice. Each turn is loaded with lots of dice & numerous choices. WHO CAN PLAY? This is truly a game for all ages! 2-4 players ages 8+. Includes 30 cards, 24 beautiful dice, and rules. Add the purple set to play with up to 8 players. Toys & Games Games & Accessories Board Games

================================================================================
QUERY: Action games for boys (keyword-based)

BM25 top 5 results:
1. (15.373) Fire Fox EPO Foam Super Durable 21.75" Hand Glider , White Firefox hand glider is perfect for the back yard, front yard and parks. It will glide for over 75 feet. Made of EPO foam, which is very flexible, makes it almost indestructible. Careful use should yield hours and hours of flying fun. No Glue or Tape required. Wingspan 22.75". Made from EPO Foam Glides 75 Feet Wingspan 21.75" Firefox hand glider is perfect for the back yard, front yard and parks It will glide for over 75 feet Made of EPO foam, which is very flexible, makes it almost indestructible Careful use should yield hours and hours of flying fun No Glue or Tape Required Toys & Games Novelty & Gag Toys Flying Toys Airplane Construction Kits
2. (11.610) smttw Wooden Sorting & Stacking Toys for 1-3 Toddlers, Montessori Toys Educational Shape Sorter Color Recognition Toys for Boys Girls, Preschool Kids Learning Puzzle Gift(4 Shapes 20 Pieces)  Entertainment & Education: This wooden sorting&stacking toy is unique and especially designed for Toddlers. It containers 20 pieces which including 4 different geometric shapes and up to 20 colors. 5 color scale from light to dark, small to large which helps to build early color, shape and size differentiation skills. Shape & Color Recognition: Toddlers' time is the best point to exercise children’s minds.This funny montessori toy is perfect for kids to learn color recognition and geometric sorting. Kids can sort by shape, by color which is helpful to build attention & patience, hand-eye coordination ability. Especially for Children: Unique & Careful design size for children which is perfect for kids to hold. Large than normal one. Smooth edges can also protect your kids’ hands very well. It is very attractive to your kids for its bright to dark colors and different geometric shapes. Perfect gift for 1-3 year old toddlers. High Quality Guarantee: We do care on kids’ products and insist on adopting super quality and safe material. This wooden sorting&stacking toy is made of 100% non-toxic wood and eco-friendly print. The edge is polished carefully to care about kids and the paint is durable. Best Choice as Gift: Montessori toy can always be the great present for your kids. What it brings is not only the educational stuff for your children, but also the happiness that around parents family with your kids. Take part in every important moment with your kids. Toys & Games Baby & Toddler Toys Early Development & Activity Toys Sorting & Stacking Toys
3. (10.675) Maomoto Cabbage Dog Plush Toys Vegetable Dog Toy, 15.7" Cabbage Shiba Inu Corgi Akita Dog Stuffed Figure, Cute Vegetables Dog Hugging Pillow, Soft Toy Children's Gift Decorations  ❤【Soft Touching】: The cute Cabbage Dog stuffed doll has an fat body, cute expression, very cute, super soft. ❤【Dimensions】: Size of Cabbage Dog: 15.7inch / 40cm. ❤【 Great plush toy friend】: Vegetables Dog Hugging Pillow is made of fine soft plush and high grade PP cotton. So super soft, comfortable, fluffy and elastic. It is very suitable for cuddling. ❤【Unique gift】:Perfect gifts for your children, lovers, friends, etc. This is not only a plush toy, but also a body pillow, which can be placed anywhere you want, such as on the bed, on the sofa, in the car, on the chair, in the children's room, and so on. ❤Suitable for children over 3 years old.It looks like cabbage, but in fact it is also a cute puppy, I am sure your child will love this unique gift as a new friend！ Toys & Games Stuffed Animals & Plush Toys Plush Pillows
4. (10.508) KINGOU Wooden Puzzle Magic Ball Brain Teasers Toy Intelligence Game Sphere Puzzles for Adults/Kids  Name: Wooden Sphere Puzzle. Please note the size: 2.36 x 2.36 x 2.36 (inch) ★KINGOU is a registered brand, the trademark number is 5034717★ Children should be used under adult supervision. It is a puzzle that will entertain and challenge all of yours Hard to take it apart, but harder to assemble. Difficulty Rated: ★★★★☆ When assembling requires careful observation and thinking, analyze its internal structure.Our mind puzzle help to exercise brain, develop intelligence, improve problem-solving ability, and also relieve pressure Tips: paper instructions and video link QR code is prepared, but in order to make it challenging and fun, we suggest you try your best to unlock this wooden ball puzzle without instruction Toys & Games Puzzles Brain Teasers Assembly & Disentanglement Puzzles
5. (10.415) QINGQIU 12 Pack Colorful Slime Eggs Toys Easter Eggs for Kids Girls Boys Easter Basket Stuffers Fillers Gifts Party Favors QINGQIU 12 Pack Colorful Slime Easter Eggs Features: 1. It's very preferential to get 12 slime easter eggs for the price, super value, order it now. 2. What a beautiful color! Get the various colors slime eggs at the party, get all the attention, share your fun with others. 3. Colorful and ranibow, not big or small, play funny, the colorful slime eggs are very suitable as an easter gift for kids boys girls easter basket stuffers. 4. Our slime is made of environmental protection material, tested safe and non-toxic, high quality, please feel free to play, but not for kids under 3 years.  Specification: Color: as the picture showed Weight: 2.3oz/egg Size: 5x6.5cm (1.97"x2.56") Package: 12 slime eggs in a box  Note: Due to temperature effects, it may not be stretchy. Soak it in hot water at 40℃ before using. After playing, put the slime back into box, can maintain softness. Don't bake! Don't eat! Only for kids 3+ Super Value - It's very preferential to get 12 slime easter eggs for the price, super value, order it now Bright Colors - What a beautiful color! Get the various colors slime eggs at the party, get all the attention, share your fun with others Slime Egg Toys - Colorful and rainbow, not big or small, play funny, the colorful slime eggs are very suitable as an easter gift for kids boys girls easter basket stuffers High Quality and Safe - Our slime is made of environmental protection material, tested safe and non-toxic, high quality, please feel free to play, but not for kids under 3 years Perfect Gift - The 12 pack colorful slime eggs are perfect for kids boys girls, easter basket stuffers, easter gifts, easter basket fillers, party favors, party supplies, stocking stuffers, christmas stockings, christmas gifts, school classroom rewards, carnival prizes, pinata, goodie bags and more Toys & Games Novelty & Gag Toys Slime & Putty Toys

Embedding search top 5 results:
1. (1.144) Spot It! Halloween From the Manufacturer Treat yourself to a game of Spot it. Halloween, but don't be tricked by the ingenious game mechanics. The award-winning game, Spot it. bewitches everyone with its fast-paced fun. Spot it. is truly a one-of-a-kind card game. Each card has 8 images of varying sizes. There is always one and only one, matching image between any 2 cards. There are 5 challenging mini-games packed into this tin. Depending on the mini-game, players simultaneously try to gain or get rid of their cards by spotting matches between 2 or 3 cards. Play your way through all the variations or just play your favorites. No matter how you play, Spot it. Halloween provides spirited competition and endless laughs. Spot it! has been bewitched with spooky symbols like jack-o'-lanterns, cobwebs, spell books, and zombies. There is always one and only one matching symbol between any two cards. Spot it fast to win! The perfect game for Halloween parties and post trick or treating fun! Develops visual perception skills, attention, and fine motor skills. A fast paced matching game for 2 to 8 players, ages 7 and up. Toys & Games Games & Accessories Card Games
2. (1.149) Who Can Do It - Compete with Your Friends to Win These Challenges [A Party Game] WHO CAN DO IT.[A Party Game] includes 250 action cards to see who in the group can do it! Compete against your friends to see WHO CAN swear in a foreign language, take the worst selfie and more 250 action cards to challenge your friends to see WHO CAN DO IT... Compete against your friends to swear in a foreign language, take the worst selfie or pretend to ride a mechanical bull Do the challenge first or best to win By the creators of the adult party game “DRUNK STONED OR STUPID” For 3+ players ages 17+ Toys & Games Games & Accessories Card Games Dedicated Deck Card Games

<div class="alert alert-info">
    
### Step 5: Web App
</div>

Please find the locally running app from this file: `app/app.py`